### PR TITLE
added react-css-modules

### PR DESCRIPTION
**Pull request by mrdivyansh**
- Added [react-css-modules](https://github.com/gajus/react-css-modules) to implement automatic mapping of CSS modules in component.
- Added [autoprefixer-loader](https://github.com/passy/autoprefixer-loader) to make cross-browser compatibility

### CODE REVIEW

**Comment by HaareeKrishna** [comment]
@mrdivyansh We use node-sass and do like `require('../styles.scss')` in component file and it will automatically map to classNames. But autoprefixer-loader is cool to add.
Can you make another PR with only autoprefixer-loader? we can merge it straightly. Thanks

**Comment by mrdivyansh** [comment]
Now, I have also changed my mind. This package should be optional and should not force to use it by add it to boilerplate.

And I am also wondering to know how we can automatically map to classNames. @HaareeKrishna  Could you please share an example.

**Comment by HaareeKrishna** [comment]
@mrdivyansh We have node-sass and sass-loader packages to compile and load scss files. So in our component file we can import its styles.scss by require('<path to scss file>') and sass-loader automatically do mapping to classNames

```
require('../styles.scss');

class Button extends React.Component {

  render() {
    return(
      <div className="main-container">
         <div className="btn">
         </div>
      </div>
    )
  }
}
```

in `../styles.scss` we can write as usual

```
.main-container {
  margin: 30px;

 .btn {
   border: 0;
  }
}
```

**Comment by mrdivyansh** [comment]
@HaareeKrishna Let me clear a confusion.

Actually, above mention example doesn't do any mapping. 
`require('../styles.scss')` only import/attach CSS rules to your application (index.html).
`<div className="main-container">` only create div with class `main-container`. Webpack doesn't do any special except importance/attachment of CSS file.

With react-css-modules, you can import CSS file as object and map css classes to elements.

**Comment by HaareeKrishna** [comment]
Yes, but we use node-sass and sass-loader which will do mapping under the hood. I am doing same in my current project and its working fine. With this boiler plate we dont have to worry about css mapping, its taken care of them. Just `require('../styles.scss')` will do trick. Thanks

**Pull request closed without merging**
